hye/hello/urls.py
from django.urls import path,re_path
from . import views

app_name = 'hello'

urlpatterns = [
    path('',views.PostListView.as_view(),name='list'),
    re_path(r'^(?P<pk>[-\w]+)/$',views.PostDetailView.as_view(),name='detail'),
    path('create',views.PostCreateView.as_view(),name='create'),
    re_path(r'^update/(?P<pk>\d+)/$', views.PostUpdateView.as_view(), name='update'),
    path('<pk>/delete/', views.PostDeleteView.as_view(), name='delete'),
]

hye/hye/urls.py
from django.contrib import admin
from django.urls import path,include
from hello import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.IndexView.as_view()),
    path('hello/',include('hello.urls',namespace='hello')),

]

hye/hello/models.py
from django.db import models
from django.urls import reverse

# Create your models here.
class Post(models.Model):
    Title = models.CharField(max_length=255)
    Text_description = models.CharField(max_length=255)

    def __str__(self):
        return self.Title

    def get_absolute_url(self):
        return reverse('hello:detail',kwargs={'pk':self.pk})

hye/hello/views.py
from django.shortcuts import render
from . import models
from django.urls import reverse_lazy
from django.views.generic import View,DetailView,ListView,DeleteView,UpdateView,CreateView,TemplateView
# Create your views here.


class IndexView(TemplateView):
    template_name = 'hello/index.html'

class PostListView(ListView):
    context_object_name = 'posts'
    model = models.Post
    template_name = 'hello/post_list.html'

class PostDetailView(DetailView):
    context_object_name = 'post_detail'
    model = models.Post
    template_name = 'hello/post_detail.html'

class PostCreateView(CreateView):
    fields = ("Title","Text_description")
    model = models.Post

class PostUpdateView(UpdateView):
    fields = ("Title","Text_description")
    model = models.Post

class PostDeleteView(DeleteView):
    model = models.Post
    success_url = reverse_lazy('hello:list')

hye/hello/templates/hello/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <!-- CSS only -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Navbar</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="#">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'hello:list' %}">Post</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'hello:create' %}">Create post</a>
        </li>
      </ul>
    </div>
  </div>
</nav>

<div class="container">
    {% block content %}

    {% endblock %}
</div>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.4/dist/umd/popper.min.js" integrity="sha384-q2kxQ16AaE6UbzuKqyBE9/u/KzioAlnx2maXQHiDX9d4/zp8Ok3f+M7DPm+Ib6IU" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.min.js" integrity="sha384-pQQkAEnwaBkjpqZ8RU1fF1AKtTcHJwFl3pblpTlHXybJjHpMYo79HY3hIi4NKxyj" crossorigin="anonymous"></script>
</body>
</html>

hye/hello/templates/hello/index.html
{% extends 'hello/base.html' %}

{% block content %}
<h3>welcome to my website</h3>
{% endblock %}

hye/hello/templates/hello/post_confirm_delete.html
{% extends 'hello/base.html' %}

{% block content %}
<h1>Delete {{post.Title}}?</h1>
<form method="post">
    {% csrf_token %}
    <input type="submit" class="btn btn-danger" value="Delete">
    <a href="{% url 'hello:detail' pk=post.pk %}">Cancel</a>
</form>
{% endblock %}

hye/hello/templates/hello/post_detail.html
{% extends 'hello/base.html' %}

{% block content %}
<div class="jumbotron">
    <h1>Welcome to the Post page</h1>
    <br>
    <h1>Post Details:</h1>
    <p>
        Title: {{ post_detail.Title }}
    </p>
    <p>
        Text description: {{ post_detail.Text_description }}
    </p>
</div>
<div class="contsiner">
    <p>
        <a class='btn btn-warning' href="{% url 'hello:update' pk=post_detail.pk %}">Update</a>
    </p>
    <p>
        <a class="btn btn-danger" href="{% url 'hello:delete' pk=post_detail.pk %}">Delete</a>
    </p>
</div>
{% endblock %}

hye/hello/templates/hello/post_form.html
{% extends 'hello/base.html' %}

{% block content %}
<h1>
    {% if not from.instance.pk %}
      Create post
    {% else %}
      Update post
    {% endif %}
</h1>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" class="btn btn-primary" value="submit">
</form>
{% endblock %}

hye/hello/templates/hello/post_list.html
{% extends 'hello/base.html' %}

{% block content %}
<h1>welcome to the list of the post</h1>
<ol>
    {% for post in posts %}
    <h2>
        <li>
            <a href="{{ post.id }}">{{ post.Title }}</a>
        </li>
    </h2>
    {% endfor %}
</ol>
{% endblock %}